using System.Windows;
using System.Windows.Controls;

namespace TileBar_from_code.View
{
    /// <summary>
    /// Interaction logic for SubCategory1View.xaml
    /// </summary>
    public partial class MainView : UserControl
    {
        public MainView()
        {
            InitializeComponent();
        }

        private void GridControl_AutoGeneratedColumns(object sender, RoutedEventArgs e)
        {

        }
    }
}
